### ISSUE TITLE
É preciso flexibilizar a detecção de códigos DOI

### ISSUE THREAD

**Issue by rafaelpezzuto** [scieloorg/scielo_scholarly_data#38]
Há algumas situações de DOIs válidos que não são detecados pelas expressões regulares usadas no método `document_doi`. As quatro expressões que esse método usa são:

1. `10.\d{4,9}/[-._;()/:A-Z0-9]+$`
2. `10.1002/[^\s]+$`
3. `10.\d{4}/\d+-\d+X?(\d+)\d+<[\d\w]+:[\d\w]*>\d+.\d+.\w+;\d$`
4. `10.1207/[\w\d]+\&\d+_\d+$`

Na linha [10](https://github.com/scieloorg/scielo_scholarly_data/blob/c48ae4e85804112d17ae1890b332bbc332c02cf8/scielo_scholarly_data/values.py#L10) há a definicção dessas expressões. Por exemplo, poderia haver uma única expressão mais abrangente que considera caracteres minúsculos (`a-z`), tal como definido em `^10.\d{4,9}/[-._;()/:A-Za-z0-9]+`.

### O que precisa ser feito
1. Testar a função atual com vários DOIs;
2. Melhorar a função atual para impedir que DOIs válidos sejam invalidados;
3. Avaliar (e implementar, se for viável) o suporte a `shortDOI`.

### Referências
1. [DOI Handbook - Sintaxe DOI](https://www.doi.org/doi_handbook/2_Numbering.html#2.2)
2. [Crossref - Estrutura de um código DOI](https://www.crossref.org/documentation/member-setup/constructing-your-dois/the-structure-of-a-doi/)
3. [DOI - shortDOI](http://shortdoi.org/)

**Comment by Rossi-Luciano** [comment]
Uma proposta foi feita no PR#44
