### ISSUE TITLE
Método para identificar se código ORCID é válido

### ISSUE THREAD

**Issue by rafaelpezzuto** [scieloorg/scielo_scholarly_data#40]
### Descrição da nova funcionalidade
Eu, como **usuário da biblioteca scielo_scholarly_data**, gostaria que **houvesse um método para identificar a validade, em termos de formato, de códigos ORCID. Um ORCID que respeita o schema v2.0 (vide referências) é composto por três partes, a saber: uri, path e host.

- uri: `http://orcid.org/0000-0002-1825-0097`
- path: `0000-0002-1825-0097`
- host: `orcid.org`

É desejável que o método permita retornar qualquer uma dessas partes. Isso seria indicado via parâmetro. Ao receber `http://orcid.org/0000-0002-1825-0097`, por exemplo, o método seria capaz de retornar qualquer um dos quatro itens:
1. `True` ou `False` (check)
2. `http://orcid.org/0000-0002-1825-0097` (uri)
3. `0000-0002-1825-0097` (path)
4. `orcid.org` (host)

### Critérios de aceitação

- Receber como entrada um código ORCID válido ou não, em sua forma completa (`http://orcid.org/0000-0002-1825-0097`) ou não (`0000-0002-1825-0097`);
- Verificar se `path` é válido;
- Retornar um dos quatro itens indicados na seção anterior.

### Referências
Verificar em [Structure of the ORCID](https://support.orcid.org/hc/en-us/articles/360006897674-Structure-of-the-ORCID-Identifier#:~:text=When%20stored%2C%20the%20ORCID%20iD,xxxx%2Dxxxx%2Dxxxx) qual é o formato ORCID esperado.

**Comment by Rossi-Luciano** [comment]
O PR Orcid validator #42 trata desta _issue_.
