### ISSUE TITLE
Não há lista de caracteres a serem removidos

### ISSUE THREAD

**Issue by rafaelpezzuto** [scieloorg/scielo_scholarly_data#43]
É desejável ser capaz de remover de um texto um certo conjunto de caracteres (para deduplicar, por exemplo, podemos sentir a necessidade de remover espaços em branco - para mesclar `alberteinstein` com `alberteinstein`, ao invés de `albert einstein` com `albert einstein`). 

Portanto, é preciso adequar as funções de posfixo `for_deduplication` para receberem uma lista de caracteres (vazia, por padrão) a serem descartados durante o tratamento do texto informado como entrada. A função deverá iterar sobre a lista de caracteres de modo a descartá-los do texto.

São três funções a serem melhoradas (em standardizer):
1. journal_title_for_deduplication
2. document_title_for_deduplication
3. document_author_for_deduplication

Deve-se aproveitar e corrigir o nome dos parâmetros atualmente existentes nas três funções (há nome de parâmetro indicado na documentação que não consta na assinatura dos métodos: por exemplo: `remove_char`). Também é preciso melhorar o nome desse parâmetro.

**Comment by Rossi-Luciano** [comment]
Essa solicitação foi implementada em um novo commit no PR#39.
